-- MySQL Script generated by MySQL Workbench
-- 11/05/14 18:10:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quail
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quail` ;

-- -----------------------------------------------------
-- Schema quail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quail` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `quail` ;

-- -----------------------------------------------------
-- Table `quail`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quail`.`product_type` ;

CREATE TABLE IF NOT EXISTS `quail`.`product_type` (
  `id` VARCHAR(60) NOT NULL,
  `num` INT NULL,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(200) NULL,
  `createTime` DATE NULL COMMENT '产品类别创建时间(排序)',
  `type` VARCHAR(10) NULL COMMENT '产品种类(0:餐饮;1:小卖部)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '产品类别(餐饮;小卖部)';


-- -----------------------------------------------------
-- Table `quail`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quail`.`department` ;

CREATE TABLE IF NOT EXISTS `quail`.`department` (
  `dept_id` VARCHAR(60) NOT NULL,
  `dept_name` VARCHAR(100) NULL COMMENT '部门名称',
  `dept_description` VARCHAR(200) NULL COMMENT '部门描述',
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB
COMMENT = '部门';


-- -----------------------------------------------------
-- Table `quail`.`support_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quail`.`support_list` ;

CREATE TABLE IF NOT EXISTS `quail`.`support_list` (
  `id` VARCHAR(60) NOT NULL,
  `list_no` VARCHAR(45) NULL COMMENT '供货列表编号',
  `reservedTime` VARCHAR(45) NULL COMMENT '供餐时间(多个时间用;分割)',
  `product_type` VARCHAR(60) NULL COMMENT '供餐类别',
  `product_id` VARCHAR(300) NULL COMMENT '菜品/商品(多个用;连接)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '供货列表';


-- -----------------------------------------------------
-- Table `quail`.`dish_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quail`.`dish_order` ;

CREATE TABLE IF NOT EXISTS `quail`.`dish_order` (
  `order_id` VARCHAR(60) NOT NULL,
  `order_no` VARCHAR(20) NULL COMMENT '订单编号',
  `user_id` VARCHAR(60) NOT NULL,
  `create_time` DATE NULL,
  `use_time` DATE NULL,
  `product_id` VARCHAR(60) NULL COMMENT '菜品/商品',
  `product_num` INT NULL COMMENT '菜品/商品数量',
  `rem` VARCHAR(45) NULL COMMENT '备注',
  `bill_status` VARCHAR(10) NULL COMMENT '订单状态（已确定，已退回，等待处理）',
  `product_status` VARCHAR(10) NULL COMMENT '商品状态(已取货,未取货)',
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
COMMENT = '订餐表';


-- -----------------------------------------------------
-- Table `quail`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quail`.`product` ;

CREATE TABLE IF NOT EXISTS `quail`.`product` (
  `id` VARCHAR(60) NOT NULL,
  `num` VARCHAR(45) NULL COMMENT '序号',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `product_type_id` VARCHAR(300) NULL COMMENT '商品/菜品 类别(多个用;连接）',
  `price` DECIMAL(2) NULL COMMENT '单价',
  `description` VARCHAR(200) NULL COMMENT '描述',
  `createTime` DATE NULL COMMENT '创建时间',
  `dept_id` VARCHAR(60) NULL COMMENT '部门',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '产品清单';


-- -----------------------------------------------------
-- Table `quail`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quail`.`user` ;

CREATE TABLE IF NOT EXISTS `quail`.`user` (
  `id` VARCHAR(60) NOT NULL,
  `minxing_id` VARCHAR(60) NULL COMMENT '敏行平台对应的ID',
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `def1` VARCHAR(45) NULL,
  `def2` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '后勤服务后台管理员';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
